In [1]:
from dataset import MultiFileDataset

import torch
from torch.utils.data import DataLoader
from model import ByteLevelTokenizer

In [2]:
dataset = MultiFileDataset("../data/raw/", 1024, 0.1, (".i"), "../data/.cache")

In [3]:
loader = DataLoader(dataset, batch_size=2, shuffle=True)

In [4]:
x = next(iter(loader))

In [5]:
x[0]

tensor([[116,  37, 120,  ..., 114, 102, 115],
        [ 37, 102,  37,  ...,  37, 106, 125]])

In [6]:
x[1]

tensor([[116,  37, 120,  ..., 114, 102, 115],
        [ 37,   0,  37,  ...,   0, 106, 125]])

In [9]:
x[1][0][100:200]

tensor([ 57,  57,  98,  98,  51,  37,  72,   0, 115,   0, 119, 110, 120,  37,
        106, 123, 106, 115,  37,   0, 114, 117, 113, 116, 126, 106, 105,  37,
         96,  96,  79,   0, 124,  98,  98, 120,  37, 110, 115,  37, 121, 109,
        106,  37,  70, 103, 124, 106, 109, 119,  37, 102, 115, 105,  37, 122,
        120, 106, 105,  37, 121,   0, 106,  37, 102,   0, 106, 115,   0, 126,
         37, 121, 116,  37, 109, 106, 113, 117,  37, 102,  37, 120, 114, 102,
        113, 113,  37, 115, 122,   0, 103, 106, 119,  37, 116,   0,  37,  79,
        106, 124])